# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends_with',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
